name: Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    name: Prepare Release
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.release.target_commitish }}

      - name: Create zip file
        run: |
          cd custom_components/openpublictransport
          zip -r ../../openpublictransport.zip .

      - name: Upload release asset
        run: gh release upload "${{ github.event.release.tag_name }}" openpublictransport.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
