name: Release

on:
  release:
    types: [published]

permissions:
  contents: write

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  release:
    runs-on: ubuntu-latest
    name: Prepare Release
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.target_commitish }}

      - name: Create zip file
        run: |
          cd custom_components
          zip -r ../openpublictransport.zip openpublictransport/

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./openpublictransport.zip
          asset_name: openpublictransport.zip
          asset_content_type: application/zip
